
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Uporter
subtitle: ""
url: "http://uporter.org"
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
# Google analytics
# ga_tracking_id: "UA-XXXX-1"

prose:
  ignore:
    - '/_layouts'
    - 'index.md'
    - '/js'
    - '/fonts'
    - '/img'
    - '/_posts'
    - '/screenshots'
    - 'Gemfile'
    - '.gitignore'
    - 'LICENSE.md'
    - 'blog.html'
    - 'contact.html'
    - 'work.html'
    - 'airspace-jekyll.gemspec'
    - '/_data'
    - '_config.yml'

# Category descriptions (for archive pages)
collections:
    subheader:
    about:
    features:
    team:
    join_us:
    reviews:
        
defaults:
  - scope:
      path: ""
    values:
      img_root: "/img/"
  - scope:
      path: _about/en
      type: about
    values:
      lang: en
  - scope:
      path: _about/de
      type: about
    values:
      lang: lt
  - scope:
      path: _about/lt
      type: about
    values:
      lang: lt
  - scope:
      path: _features/en
      type: features
    values:
      lang: en
  - scope:
      path: _features/de
      type: features
    values:
      lang: de
  - scope:
      path: _features/lt
      type: features
    values:
      lang: lt
  - scope:
      path: _team
    values:
      img_root: "/team/"
  - scope:
      path: _team/en
      type: team
    values:
      lang: en
  - scope:
      path: _team/de
      type: team
    values:
      lang: de
  - scope:
      path: _team/lt
      type: team
    values:
      lang: lt
  - scope:
      path: _join_us/en
      type: join_us
    values:
      lang: en
  - scope:
      path: _join_us/de
      type: join_us
    values:
      lang: de
  - scope:
      path: _join_us/lt
      type: join_us
    values:
      lang: lt
  - scope:
      path: _reviews/en
      type: reviews
    values:
      lang: en
  - scope:
      path: _reviews/de
      type: reviews
    values:
      lang: de
  - scope:
      path: _reviews/lt
      type: reviews
    values:
      lang: lt
  - scope:
      path: _subheader/en
      type: subheader
    values:
      lang: en
  - scope:
      path: _subheader/de
      type: subheader
    values:
      lang: de
  - scope:
      path: _subheader/lt
      type: subheader
    values:
      lang: lt